{
    'name': 'Timesheet Work',
    'version': '14.0.8.0.2',
    'category': '',
    'description': u"""
Work sheet resume with time, products and expenses.
Printed format as receipt to customer.
""",
    'author': 'Serincloud',
    'depends': [
        'base_automation',
        'purchase',
        'stock',
        'account',
        'hr_expense',
        'sale_timesheet',
        'hr_timesheet_time_type',
        'hr_timesheet_begin_end',
        'analytic_line_tracking',
        'web_widget_open_tab',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/rules.xml',
        'data/action_server.xml',
        'views/timesheet_work_views.xml',
        'views/work_picking_wizard_views.xml',
        'views/work_timesheet_wizard_views.xml',
        'views/work_sheet_views.xml',
        'views/stock_picking_views.xml',
        'views/account_analytic_line_views.xml',
        'views/templates.xml',
        'views/work_sheet_report.xml',
        'views/hr_employee.xml',
        'views/timesheet_line_todo_views.xml',
        'views/timesheet_line_done_views.xml',
        'views/sale_order_views.xml',
        'views/hr_expense_views.xml',
        'views/project_time_type_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
}
