# Copyright Serincloud SL - 2023
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

{
    "name": "Shoes dealer",
    "summary": "Assortments, Pairs and BOM automation.",
    "version": "16.0.2.0.1",
    "category": "stock",
    "author": "Serincloud SL",
    "website": "https://www.ingenieriacloud.com",
    "license": "AGPL-3",
    "depends": [
        # ODOO:
        "crm",
        "sale_management",
        "purchase",
        "stock",
        "mrp",
        "sale_mrp",
        "project",
        "sale_product_template_tags",
        "base_automation",
        "website_sale",
        "partner_commission",
        "uom",
        # PUNT:
        "partner_commission_manager_ee",
        # OCA:
        "product_brand",
        "product_net_weight",
        "sale_order_line_date",
        "sale_order_line_menu",
        "product_variant_sale_price",
        "sale_product_image",
    ],
    "data": [
        "wizard/pnt_product_report_wizard_view.xml",
        "data/server_actions.xml",
        "security/ir.model.access.csv",
        "views/set_template_views.xml",
        "views/product_template_views.xml",
        "views/product_product_views.xml",
        "views/res_company_views.xml",
        "views/product_attribute_views.xml",
        "views/sale_order_views.xml",
        "views/sale_order_line_views.xml",
        "views/purchase_order_views.xml",
        "views/account_move_views.xml",
        "views/product_material_views.xml",
        "views/mrp_bom_views.xml",
        "views/project_project_views.xml",
        "views/sale_report_views.xml",
        "views/shoes_report_views.xml",
        "data/automatic_actions.xml",
        "reports/pnt_product_report.xml",
        "reports/pnt_product_report_template.xml",
        "views/res_users_views.xml",
        "views/stock_picking_views.xml",
        "views/stock_orderpoint_views.xml",
        "views/account_move_line_views.xml",
        "views/shoes_pair_weight_views.xml",
    ],
    "installable": True,
}
