# Copyright 2023 Serincloud SL.
# License AGPL-3 - See http://www.gnu.org/licenses/agpl-3.0.html

{
    "name": "Custom Azarey",
    "summary": "Customs Azarey",
    "version": "16.0.1.0.0",
    "category": "Sales",
    "author": "Serincloud SL",
    "website": "https://www.ingenieriacloud.com",
    "license": "AGPL-3",
    "depends": [
        "product",
        "mail",
        "contacts",
        "sale_management",
        "partner_multi_relation",
        "mrp",
        "l10n_es_partner",
        "stock",
        "product_variant_sale_price",
        "project",
        "account_financial_risk",
        "sale_financial_risk",
        "pnt_product_ean_barcode",
        "report_csv",
    ],
    "data": [
        "views/product_attribute_views.xml",
        "views/product_pricelist_views.xml",
        "views/project_task_views.xml",
        "views/project_project_views.xml",
        "views/product_template_views.xml",
        "views/product_product_views.xml",
        "views/res_company_views.xml",
        "views/res_partner_views.xml",
        "views/sale_order_views.xml",
        "reports/pricelist_report.xml",
        "reports/product_pricelist_report_template.xml",
        "reports/pnt_report_invoice.xml",
        "reports/pnt_sale_order.xml",
        "reports/pnt_report_purchase_order.xml",
        "reports/product_product_templates.xml",
        "reports/product_template_report.xml",
        "reports/pnt_stock_picking_label.xml",
        "reports/pnt_stock_picking_templates.xml",
        "reports/pnt_product_catalog_csv.xml",
        "wizard/pnt_product_pricelist_report_wizard_view.xml",
        "reports/project_task_report.xml",
        "reports/project_task_report_template.xml",
        "wizard/pnt_project_task_report_wizard_view.xml",
        "security/ir.model.access.csv",
    ],
    "qweb": [
        "static/src/xml/chatter_sale_order.xml",
    ],
    "installable": True,
}
